language: python
python:
- '2.7'
install: pip install -r requirements.txt
script:
- APP_SETTINGS="config.TestingConfig" python tests.py
env:
  global:
  - NOTIFY_TEST_REMOTE_BROWSER=YES
  - APP_SETTINGS="config.StagingConfig"
  - DATABASE_URL="postgres://travis:@localhost/travis_ci_test"
  - BROWSERID_URL="http://localhost:5000/"
  - secure: huYEM/SnM0kUu6Vt3Ez9NKWmpDr9g0M8JeQvumUdPLDHTz9dntuScrypQ6cZVXBSdu99Of0F6EEwKhlK4UtY4Nfs742gLqKPY2aH+QZiK07z1iGjfdE4vWT7BXKmZ4reSJsRqCGPYMUi/yY7J6VlyHoeeONCTcUYlt/XZfpzFYyP0TAYInnMas9jrGUQ7LSIOxKIboST1mSPg1HPWwscOYzg3QZ2+ANE1X2ToWV4TYRsH/IozqTZs84Q/rP63zQqn2jQPqe3gFt9qVtSLL5+ylbsKutUwg5mwq8I9PcBlLaNToJxYEdAPjDWbFjY/Q/7ls3oel5Zr/P/enR+jvuQEqh3vX+aHajaJJTecXWcpDTDHufc3Zz/MVPD6Iq5IXNS7HK1J0gyAxALP7n79hngehyGqNn/93sdk01C0Sqx6QPASNtyziNaj1tyCEhcS5REKu+ySlwAl+8KwsAq/cd6DYtK8DvaiZPKwKcA+j2BK3xZyN082+n1g0HlPNY6dRcl1SVZwRk0l1Y1KqTnYCCVFTnDWNUjgmWDcUY2q5QKfLPpnuBb6FVgPFuBh+0W6tcffxBlfDJifKg2UcWR+Lmcft0rBZI9n3cR/foSRZDrEKlNNiGEITPPm9rhUBz9v5+bvNcZJCLIN9L8KpJ0oczEu0RX0wn9NjLBlerMofB0J8s=
  - secure: XphKHP0c8I0dAeqDFoJLKcmdZa0AlT9rqGXXxSViWp2QGfSquv5NiGqB7wDFcoppHNX0Xu/BeKUQFTCYNrUsZELAcWht6gcje6SMTxblRPofoVF0hJ/exNR//eeAc5eVdjetHXUTdHTSQaPUqRZXxy9oEe3OR4lqp8DGpAlw12XUxqVs7g9WDcPKIHepoGxgM2900PTrI4BouxnCYwdPqrVBdFyK2GI3LQ227LN94Qlb9hISGXGvRiIcSTQp0IlZ9FSj9yckF729SbFIsiyOIw6D1GIdgSQeESCi+lJiNrUH0ukUChgC7IqXaOhT0IGIdK2huQBjNODJ2yPnftozFMKHWKTLI+O1zyFWB/zDYmPr0PsgvS8BbRWeWjv5XMcXOtAgaKGBHWBHrCc0lD4oniKyH5+TNvWucakxvZ7XThzcXbyLXcebnZ/g0uiOwgC+8xCnGPdzxqnvHFxTrhphhgiXG6UNN3T5pK/7ss7PjkfwjwsoLG9GcZ3AFtvve0UqtKQC0v90RUSzE8stlE6XM+LmZ7T+OwV4H4MLX6I1X9UhC3f+njpgANE28pjFdX4Mql+fHKQfu67vjOjDWGXLnjNVWuHIVUl2w3ba9FRQsNGv7Imk8ENOKi+T1ejnX+Ml+hYemWsoXAKPK54BdEG1CteaEFoIsJJ6iA9sSrXGj1g=
  - secure: UUaWOhP2EW7E6lUyLSeWtwPGluEpdOzPeqvdPZ8ayPkWTkVBEdQA5U/bOUSgFEYj5UA43WsaX0UDnxxO9bgO2svkeMUriLuoz3d0w/Mb7CsCqLiHzOTBq5b2PIfit8pcT7L3g+x9PrtZAs9nGAk7tRCmMBL3ZhMd8m+LHD47d2e8aLEnuiq5HK+d5WENj0XH3UuE0tKj2RQdFO2z8pkLn6UzkdyoBvtk2Hl9/hK4ZEjxwM7s7Tu2Aypx+JXSzUQuO0+iP3gHGi77HP77neMmltnSNVLor2Bz4640TQai1hST6acBa7Ml6CejC7GgVdTdAO7D4VfvqMI2i4QvbHwe2UZ25leWsAKZAPHZLKr8JsSDjHh09GtMj+t+Xwcu/SnQLIMP+UuebTTkpIA+1Q7sg8o7KcZJM24HEoYgTA5VWvmSwfK6kq97eSzOMPHjsQZyFEwuCh9uKABGCyK7jtTVWVoGPgS2bvnztaOFMFZaCUIaFiMY3q0GOdAv20frPLRvq5VvcxBM1SbjrL1wvmFlpgpSjTRt3PbraNYPkr48BkMgM9xI0pnnHIgAm+ifYSgMnI57eDsUOGM2T5iCdX8+6Om8un5tHbFuS73fVHVibSszPwtzTagVFcee03SYH2u/7VnbFc4vwwDACwLlO0y/B4sbpmujv0m/e+pVG99arqQ=
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- alembic upgrade head
- python app.py &
addons:
  sauce_connect: true
